// Home
export const CUSTOM_PICKER_VALUE_CHANGE = 'CUSTOM_PICKER_VALUE_CHANGE';

// News 
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAIL = "FETCH_NEWS_FAIL";
export const NEWS_OVERLAY_COLOR = "NEWS_OVERLAY_COLOR";
export const NEWS_IMPRESSION = "NEWS_IMPRESSION";